[package]
name = "webauthn-rs-error"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64.workspace = true
serde_cbor_2.workspace = true
serde_json.workspace = true
thiserror.workspace = true
